package org.androidtown.moneymanagement.Common;

public enum Mode {
    SEARCH_STUDENT_FRAGMENT,
    SEARCH_ONLY_ACTIVITY,
    ENROLL_FRAGMENT,
    ENROLL_NEWBIE_ACTIVITY,
    ENROLL_CHECK_POPUP,
    DELETE_CHECK_POPUP,
    MANAGE_FRAGMENT,
    DETAIL_INFO_POPUP,

    SID_SEARCH,
    SID_ENROLL,
    YEAR,

    MODIFY,


}
